### PR TITLE
Completed week2 --Neil

### PR DESCRIPTION
**Pull request by NEIL-smtg**
Completed week2 exercises

### CODE REVIEW

**Comment by v-wuzhai** [comment]
image


Looks like the implementation failed to run correctly.

**Comment by NEIL-smtg** [comment]
I have added the instruction to run the program in README.md

Example to run:
dotnet run 3 + 2
dotnet run 3 * 9

**Comment by v-wuzhai** [comment]
image
Looks like this calculation is incorrect.

**Comment by v-wuzhai** [comment]
image
Looks like this shape is incorrect.

**Comment by NEIL-smtg** [comment]
image

I have fixed the error.

**Pull request merged**
