### PR TITLE
Syareel Week 2

### PR DESCRIPTION
**Pull request by Syareel-Sukeri**
**Thank you for the exercise**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
Please take a look here： https://github.com/v-wuzhai/MY_C-_Practise/pull/40#issuecomment-2257888754

**Comment by Syareel-Sukeri** [comment]
Done update according to instruction

**Comment by v-wuzhai** [comment]
The Sequence project should follow the same logic.

**Comment by Syareel-Sukeri** [comment]
Done updating Sequence project

**Pull request merged**
