### PR TITLE
Week 1_ RAMANAN

### PR DESCRIPTION
**Pull request by Ramanan0508**
This is first week assignment
- Concatenate
- trim
- replace
- upper/lower case
- length
- contains

### CODE REVIEW

**Comment by v-wuzhai** [comment]
Please look here：https://github.com/v-wuzhai/MY_C-_Practise/pull/7#issuecomment-2235195111

**Comment by Ramanan0508** [comment]
@v-wuzhai Done updated

**Comment by v-wuzhai** [comment]
You can see there are many conflicts. Resolve them, or delete and redo.

**Comment by v-wuzhai** [comment]
I will close this pr and you can do it again.

**Pull request closed without merging**
