### PR TITLE
week1_homework

### PR DESCRIPTION
**Pull request by Liv-Goh**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
Please change your project’s working directory, it should be: week1 - folder (your name) - project.

**Comment by Liv-Goh** [comment]
> Please change your project’s working directory, it should be: week1 - folder (your name) - project.

Updated

**Comment by v-wuzhai** [comment]
Can you add a .md file to describe this project?

**Comment by v-wuzhai** [comment]
It looks good, but the execution program flashes and disappears when opened. It would be better if the command window could remain open.

**Pull request merged**
