### PR TITLE
Week 1

### PR DESCRIPTION
**Pull request by farisafiqnex**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@farisafiqnex Can you add a .md file to this project?

**Comment by farisafiqnex** [comment]
Hi @v-wuzhai
I have added the readme.md file. However I noticed there are many conflicts. Would you suggest I start over or try to solve it?

**Comment by v-wuzhai** [comment]
I will close this pr and you can do it again.

**Comment by farisafiqnex** [comment]
Alright, thanks @v-wuzhai

**Pull request closed without merging**
