### PR TITLE
Syahmie W1 Work

### PR DESCRIPTION
**Pull request by SyahmieS**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
Please look here：https://github.com/v-wuzhai/MY_C-_Practise/pull/7#issuecomment-2235195111

**Comment by v-wuzhai** [comment]
Move the file to your project directory (the project directory should be the MottoMotto folder).

**Comment by SyahmieS** [comment]
Hi @v-wuzhai, can you check again? I have added the READMe.md as requested.

**Comment by v-wuzhai** [comment]
image

Please address the issues mentioned in the comments.

**Comment by SyahmieS** [comment]
@v-wuzhai, can you check again? I have moved these files as requested.

**Pull request merged**
