### PR TITLE
WEEK 2 (ATIF)

### PR DESCRIPTION
**Pull request by atifwajdi**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
image

Looks like the implementation failed to run correctly.

**Comment by atifwajdi** [comment]
I already fix this error.

**Comment by v-wuzhai** [comment]
image

Looks like this calculation is incorrect.

**Comment by atifwajdi** [comment]
@v-wuzhai , I already fix the error for the divide problem. 
Screenshot 2024-07-30 165330
The output should be like in the picture.

**Comment by v-wuzhai** [comment]
Your ‘Diamond’ project doesn’t meet the requirements. It should take an input value and then output the corresponding shape based on that value.

**Comment by atifwajdi** [comment]
@v-wuzhai , done fix the diamond project requirement. 

image

**Pull request merged**
