### PR TITLE
Week 1 Homework (Atif)

### PR DESCRIPTION
**Pull request by atifwajdi**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@atifwajdi Can you add a .md file to this project?

**Comment by atifwajdi** [comment]
done

**Comment by v-wuzhai** [comment]
Please look here：https://github.com/v-wuzhai/MY_C-_Practise/pull/7#issuecomment-2235195111

**Comment by atifwajdi** [comment]
Done update

**Comment by atifwajdi** [comment]
Hi @v-wuzhai, can you check again? I have added the READMe.md and change the project’s working directory as requested.

**Comment by v-wuzhai** [comment]
image

Please address the issues mentioned in the comment.

**Comment by atifwajdi** [comment]
Done update

**Pull request merged**
