### PR TITLE
Completed week3 -- Neil

### PR DESCRIPTION
**Pull request by NEIL-smtg**
Completed week3 exercise

Example run:

1. cd week3\Neil\TwoSum
2. dotnet run
3. follow the instructions from the program

### CODE REVIEW

**Comment by v-wuzhai** [comment]
image
When I input the format incorrectly, shouldn’t you give a prompt?

**Comment by NEIL-smtg** [comment]
image

I have thrown an exception error when user enter an invalid input.

**Comment by v-wuzhai** [comment]
> image
> The program will throw an exception error when user enter an invalid input.

My intention was to ask for a hint, but it’s okay for now. Let’s leave it at that.

**Comment by v-wuzhai** [comment]
image
The result should have two sets of solutions.

**Comment by NEIL-smtg** [comment]
Originally, the code I wrote can handled more than 1 solution but until I saw this:

image

**Comment by v-wuzhai** [comment]
This is just an example.

**Comment by NEIL-smtg** [comment]
@v-wuzhai I have committed a fix for that.

**Pull request merged**
