### PR TITLE
MyAmar1 Week 1 Exercise Done. 

### PR DESCRIPTION
**Pull request by Amar-QA**

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@Amar-QA Can you add a .md file to this project?

**Comment by Amar-QA** [comment]
@v-wuzhai Hi there, I have added the MD file to describe the project.

**Comment by v-wuzhai** [comment]
Please look here：https://github.com/v-wuzhai/MY_C-_Practise/pull/7#issuecomment-2235195111

**Comment by Amar-QA** [comment]
@v-wuzhai Changed the project directory.

**Comment by Amar-QA** [comment]
@v-wuzhai Moved All the Related Files into Week1 / "Amarnath" Directory. Please get back to me if any further changes. Thank You.

**Comment by v-wuzhai** [comment]
image
It looks like the `dotnet build` failed. Removing the .sln file might solve the problem

**Pull request merged**
